title: "Blog de Análisis de Datos"
description: "Proyecto de flujo de clics con Spark y Jekyll"
author: "Alessandro Díaz M."
theme: jekyll-theme-cayman

# Configuración de baseurl vacía (para localhost)
baseurl: ""
url: "http://localhost:4000"

# Incluir posts y páginas
include:
  - _posts
  - assets

# Plugins opcionales
plugins:
  - jekyll-feed
