title: "Blog de An√°lisis de Datos"
description: "Proyecto de flujo de clics con Spark y Jekyll"
theme: jekyll-theme-cayman

url: "https://alexioscrane99.github.io"
baseurl: "/mi-blog"

collections:
  posts:
    output: true

include:
  - assets
